"""First migrate

Revision ID: fd38abf01eb6
Revises: 
Create Date: 2024-02-19 09:38:25.058064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd38abf01eb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=1000), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('coffee_rating', sa.String(length=20), nullable=False),
    sa.Column('wifi_rating', sa.String(length=20), nullable=False),
    sa.Column('power_avail', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
